version: '3'

services: 
  nginx:
    restart: always
    image: $BUILD_NGINX
    networks:
      - django_net
    ports:
      - "$PORT:8000"

  db:
    restart: always
    image: "postgres:14"
    networks:
      - django_net
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    restart: always
    image: $BUILD_DJANGO
    networks:
      - django_net
    expose:
      - "8000"
    depends_on: 
      db:
        condition: service_healthy
    depends_on:
      - nginx
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

networks:
  django_net:
